name: Munit Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Where is brew?
        run: which brew
      - name: Run tests
        run: make test
